let timerInterval=null,totalSeconds=0,initialSeconds=0;
function changeValue(id,amount){const input=document.getElementById(id);let value=parseInt(input.value)||0;value+=amount;if(id==="minutes"||id==="seconds")value=Math.max(0,Math.min(59,value));if(id==="hours")value=Math.max(0,Math.min(99,value));input.value=value;}
function setTimer(hours,minutes,seconds){document.getElementById("hours").value=hours;document.getElementById("minutes").value=minutes;document.getElementById("seconds").value=seconds;updateDisplay(hours,minutes,seconds);}
function updateDisplay(hours,minutes,seconds){document.getElementById("hoursDisplay").textContent=String(hours).padStart(2,"0");document.getElementById("minutesDisplay").textContent=String(minutes).padStart(2,"0");document.getElementById("secondsDisplay").textContent=String(seconds).padStart(2,"0");}
function scheduleShutdown(){const hours=parseInt(document.getElementById("hours").value)||0;const minutes=parseInt(document.getElementById("minutes").value)||0;const seconds=parseInt(document.getElementById("seconds").value)||0;totalSeconds=hours*3600+minutes*60+seconds;if(totalSeconds<=0){showMessage("Informe um tempo válido.");return;}initialSeconds=totalSeconds;clearInterval(timerInterval);timerInterval=setInterval(()=>{if(totalSeconds<=0){clearInterval(timerInterval);showMessage("Desligamento iniciado.");return;}totalSeconds--;updateTimer();},1000);showMessage("Desligamento agendado.");updateTimer();}
function updateTimer(){const hours=Math.floor(totalSeconds/3600);const minutes=Math.floor((totalSeconds%3600)/60);const seconds=totalSeconds%60;updateDisplay(hours,minutes,seconds);const progress=((initialSeconds-totalSeconds)/initialSeconds)*100;document.getElementById("progressBar").style.width=`${progress}%`;document.getElementById("progressPercent").textContent=`${Math.round(progress)}%`;}
function cancelShutdown(){clearInterval(timerInterval);totalSeconds=0;updateDisplay(0,0,0);document.getElementById("progressBar").style.width="0%";document.getElementById("progressPercent").textContent="0%";showMessage("Desligamento cancelado.");}
function shutdownNow(){showMessage("Desligamento iniciado.");}
function showMessage(message){document.getElementById("statusMessage").textContent=message;}
function copyCommand(){const command=document.getElementById("commandText").textContent;navigator.clipboard.writeText(command);showMessage("Comando copiado.");}
